### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by cpear** [velocitysystems/stopwatch#1]
I will probably sound like a jerk for asking but I noticed there is no license file for this stopwatch repo. I may want to use this as a base for an app I would like to build. I just to make sure its ok to do that before I do. Would you mind adding one? Thank you so much.

**Comment by velocitysystems** [comment]
No worries @cpear. This repo is now available under the MIT license. Thanks!
https://github.com/velocitysystems/stopwatch/blob/master/LICENSE
